# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = ""
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "hotwax-gift-wrapper"
handle = "hotwax-gift-wrapper"

# name = "practice-gift-wrapper"
# handle = "practice-gift-wrapper"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_draft_orders, write_draft_orders, read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "hotwax-dev.myshopify.com"
include_config_on_deploy = true
